/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package eShopPackage;

import java.awt.CardLayout;
import java.awt.event.ActionEvent;
import java.util.List;
import javax.swing.JComboBox;
import java.util.ArrayList;
import java.util.Map;
import javax.swing.JOptionPane;

/**
 *
 * @author dimit
 */
public class Main extends javax.swing.JFrame {

    CardLayout cardLayout,cardAdd,cardEdit;
    
    
    public Main() {
        initComponents();
        cardLayout = (CardLayout)(NewFrame.getLayout());
        cardAdd = (CardLayout)(NewFrame2.getLayout());
        cardEdit = (CardLayout)(NewFrame3.getLayout());
    }
   
    private void populateCategory(JComboBox<String> comboBox) {      
    comboBox.removeAllItems();
    comboBox.addItem("");
    DatabaseConnection dbConnection = new DatabaseConnection();
    DataAccessObject categoryDAO = new DataAccessObject(dbConnection);
    Map<Integer, String> categories = categoryDAO.getCategoryNames();
    
    for (Map.Entry<Integer, String> entry : categories.entrySet()) {
        comboBox.addItem(entry.getValue());
        comboBox.putClientProperty(entry.getValue(), entry.getKey()); // Store the ID as a property
    }
    dbConnection.closeConnection();
    }
    
    private void populateSubCategory(JComboBox<String> comboBox, int categoryId) {
    comboBox.removeAllItems();
    comboBox.addItem("");
    DatabaseConnection dbConnection = new DatabaseConnection();
    DataAccessObject categoryDAO = new DataAccessObject(dbConnection);
    Map<Integer, String> subCategories = categoryDAO.getSubCategoryNames(categoryId);
    
    for (Map.Entry<Integer, String> entry: subCategories.entrySet()) {
        comboBox.addItem(entry.getValue());
        comboBox.putClientProperty(entry.getValue(), entry.getKey()); // Store the ID as a property
    }
    dbConnection.closeConnection();
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        MainNavegationPanel = new javax.swing.JPanel();
        userName = new javax.swing.JLabel();
        timeLabel = new javax.swing.JLabel();
        SettingsButton = new javax.swing.JButton();
        ManagerButton = new javax.swing.JButton();
        NewFrame = new javax.swing.JPanel();
        StocksPanel = new javax.swing.JPanel();
        AddNewNames = new javax.swing.JPanel();
        SubNavigationBar = new javax.swing.JPanel();
        NewCategoryButton = new javax.swing.JButton();
        NewSubCategoryButton = new javax.swing.JButton();
        NewProductButton = new javax.swing.JButton();
        SubNavigationLabel = new javax.swing.JLabel();
        NewFrame2 = new javax.swing.JPanel();
        empty = new javax.swing.JPanel();
        AddCategory = new javax.swing.JPanel();
        NewPanelCategoryName = new javax.swing.JLabel();
        NewPanelCategoryNameField = new javax.swing.JTextField();
        NewPannelAddCategoryButton = new javax.swing.JButton();
        AddSubCategory = new javax.swing.JPanel();
        NewSubCategorySubName = new javax.swing.JTextField();
        NewSubCategoryAddButton = new javax.swing.JButton();
        NewSubCategorySub = new javax.swing.JLabel();
        NewSubCategoryCategoryComboBox = new javax.swing.JComboBox<>();
        NewSubCategoryCategory = new javax.swing.JLabel();
        AddProducts = new javax.swing.JPanel();
        NewCategoryProdactLabel = new javax.swing.JLabel();
        AddNewProdactButton = new javax.swing.JButton();
        NewProdactNameLabel = new javax.swing.JLabel();
        PanelProdactCategorySelect = new javax.swing.JComboBox<>();
        PanelProdactSubCategorySelect = new javax.swing.JComboBox<>();
        NewSubCategoryProdactLabel = new javax.swing.JLabel();
        NewProdactStockField = new javax.swing.JTextField();
        NewProdactPriceField = new javax.swing.JTextField();
        NewProdactStockLabel = new javax.swing.JLabel();
        NewProdactPriceLabel = new javax.swing.JLabel();
        NewProdactDescriptionField = new javax.swing.JLabel();
        NewProdactNameField = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        NewProdactDescription = new javax.swing.JTextArea();
        EditNames = new javax.swing.JPanel();
        SubNavigationBar1 = new javax.swing.JPanel();
        EditCategoryButton = new javax.swing.JButton();
        EditSubCategoryButton = new javax.swing.JButton();
        EditProductButton = new javax.swing.JButton();
        SubNavigationLabel1 = new javax.swing.JLabel();
        NewFrame3 = new javax.swing.JPanel();
        empty1 = new javax.swing.JPanel();
        EditCategory = new javax.swing.JPanel();
        EditCategoryName = new javax.swing.JLabel();
        EditCategoryField = new javax.swing.JTextField();
        AddEditCategoryButton = new javax.swing.JButton();
        SelectCategoryComboBox1 = new javax.swing.JComboBox<>();
        EditCategoryName1 = new javax.swing.JLabel();
        EditSubCategory = new javax.swing.JPanel();
        EditSubCategoryField = new javax.swing.JTextField();
        AddNewSubCategoryButton1 = new javax.swing.JButton();
        EditSubCategoryName = new javax.swing.JLabel();
        SelectCategoryComboBox2 = new javax.swing.JComboBox<>();
        NewCategoryProdactLabel3 = new javax.swing.JLabel();
        NewCategoryProdactLabel4 = new javax.swing.JLabel();
        EditSubCategoryComboBox = new javax.swing.JComboBox<>();
        EditProducts = new javax.swing.JPanel();
        EditCategoryProdactLabel = new javax.swing.JLabel();
        EditProdactNameButton = new javax.swing.JButton();
        EditProdactNameLabel = new javax.swing.JLabel();
        EditProdactCategorySelect = new javax.swing.JComboBox<>();
        EditProdactSubCategorySelect = new javax.swing.JComboBox<>();
        EditSubCategoryProdactLabel = new javax.swing.JLabel();
        EditProdactDescriptionField = new javax.swing.JLabel();
        EditProdactNameField = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        EditProdactDescription = new javax.swing.JTextArea();
        EditProdactLabel = new javax.swing.JLabel();
        EditProdactSelect = new javax.swing.JComboBox<>();

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        MainNavegationPanel.setBackground(new java.awt.Color(0, 153, 153));

        userName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        userName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userName.setText("Dimitris");

        timeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        timeLabel.setText("2024-2025");

        SettingsButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        SettingsButton.setText("Επεξεργασία");
        SettingsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SettingsButtonActionPerformed(evt);
            }
        });

        ManagerButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ManagerButton.setText("Προσθήκη Νέων");
        ManagerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManagerButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MainNavegationPanelLayout = new javax.swing.GroupLayout(MainNavegationPanel);
        MainNavegationPanel.setLayout(MainNavegationPanelLayout);
        MainNavegationPanelLayout.setHorizontalGroup(
            MainNavegationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainNavegationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MainNavegationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainNavegationPanelLayout.createSequentialGroup()
                        .addComponent(userName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainNavegationPanelLayout.createSequentialGroup()
                        .addComponent(timeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainNavegationPanelLayout.createSequentialGroup()
                        .addComponent(SettingsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainNavegationPanelLayout.createSequentialGroup()
                        .addComponent(ManagerButton, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        MainNavegationPanelLayout.setVerticalGroup(
            MainNavegationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainNavegationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(userName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(ManagerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SettingsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(timeLabel)
                .addContainerGap())
        );

        NewFrame.setBackground(new java.awt.Color(255, 255, 255));
        NewFrame.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout StocksPanelLayout = new javax.swing.GroupLayout(StocksPanel);
        StocksPanel.setLayout(StocksPanelLayout);
        StocksPanelLayout.setHorizontalGroup(
            StocksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1076, Short.MAX_VALUE)
        );
        StocksPanelLayout.setVerticalGroup(
            StocksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 708, Short.MAX_VALUE)
        );

        NewFrame.add(StocksPanel, "card2");

        SubNavigationBar.setBackground(new java.awt.Color(0, 102, 102));

        NewCategoryButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        NewCategoryButton.setText("Κατηγοριές");
        NewCategoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewCategoryButtonActionPerformed(evt);
            }
        });

        NewSubCategoryButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        NewSubCategoryButton.setText("Υποκατηγορίες");
        NewSubCategoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewSubCategoryButtonActionPerformed(evt);
            }
        });

        NewProductButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        NewProductButton.setText("Προϊοντα");
        NewProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewProductButtonActionPerformed(evt);
            }
        });

        SubNavigationLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        SubNavigationLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SubNavigationLabel.setText("Προσθήκη Νέων");

        javax.swing.GroupLayout SubNavigationBarLayout = new javax.swing.GroupLayout(SubNavigationBar);
        SubNavigationBar.setLayout(SubNavigationBarLayout);
        SubNavigationBarLayout.setHorizontalGroup(
            SubNavigationBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SubNavigationBarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SubNavigationBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SubNavigationBarLayout.createSequentialGroup()
                        .addGroup(SubNavigationBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NewProductButton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NewCategoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NewSubCategoryButton))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(SubNavigationLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        SubNavigationBarLayout.setVerticalGroup(
            SubNavigationBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SubNavigationBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SubNavigationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(NewCategoryButton)
                .addGap(18, 18, 18)
                .addComponent(NewSubCategoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(NewProductButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        NewFrame2.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout emptyLayout = new javax.swing.GroupLayout(empty);
        empty.setLayout(emptyLayout);
        emptyLayout.setHorizontalGroup(
            emptyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 926, Short.MAX_VALUE)
        );
        emptyLayout.setVerticalGroup(
            emptyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 701, Short.MAX_VALUE)
        );

        NewFrame2.add(empty, "cardNewEmpty");

        NewPanelCategoryName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        NewPanelCategoryName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NewPanelCategoryName.setText("Νέο Όνομα Κατηγορίας:");

        NewPanelCategoryNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewPanelCategoryNameFieldActionPerformed(evt);
            }
        });

        NewPannelAddCategoryButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        NewPannelAddCategoryButton.setText("Submit");
        NewPannelAddCategoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewPannelAddCategoryButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AddCategoryLayout = new javax.swing.GroupLayout(AddCategory);
        AddCategory.setLayout(AddCategoryLayout);
        AddCategoryLayout.setHorizontalGroup(
            AddCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddCategoryLayout.createSequentialGroup()
                .addGap(313, 313, 313)
                .addGroup(AddCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(NewPannelAddCategoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NewPanelCategoryNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NewPanelCategoryName, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(313, Short.MAX_VALUE))
        );
        AddCategoryLayout.setVerticalGroup(
            AddCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddCategoryLayout.createSequentialGroup()
                .addGap(201, 201, 201)
                .addComponent(NewPanelCategoryName, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(NewPanelCategoryNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(NewPannelAddCategoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(314, Short.MAX_VALUE))
        );

        NewFrame2.add(AddCategory, "cardNewCategory");

        NewSubCategorySubName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewSubCategorySubNameActionPerformed(evt);
            }
        });

        NewSubCategoryAddButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        NewSubCategoryAddButton.setText("Submit");
        NewSubCategoryAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewSubCategoryAddButtonActionPerformed(evt);
            }
        });

        NewSubCategorySub.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        NewSubCategorySub.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NewSubCategorySub.setText(" Νέο Όνομα Υποκατηγορίας:");

        NewSubCategoryCategoryComboBox.setName(""); // NOI18N
        NewSubCategoryCategoryComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewSubCategoryCategoryComboBoxActionPerformed(evt);
            }
        });

        NewSubCategoryCategory.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        NewSubCategoryCategory.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NewSubCategoryCategory.setText("Επιλογή Κατηγορίας:");

        javax.swing.GroupLayout AddSubCategoryLayout = new javax.swing.GroupLayout(AddSubCategory);
        AddSubCategory.setLayout(AddSubCategoryLayout);
        AddSubCategoryLayout.setHorizontalGroup(
            AddSubCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddSubCategoryLayout.createSequentialGroup()
                .addGap(313, 313, 313)
                .addGroup(AddSubCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(NewSubCategoryAddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NewSubCategoryCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NewSubCategoryCategoryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NewSubCategorySub, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NewSubCategorySubName, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(313, Short.MAX_VALUE))
        );
        AddSubCategoryLayout.setVerticalGroup(
            AddSubCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddSubCategoryLayout.createSequentialGroup()
                .addContainerGap(196, Short.MAX_VALUE)
                .addComponent(NewSubCategoryCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(NewSubCategoryCategoryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(NewSubCategorySub, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(NewSubCategorySubName, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(NewSubCategoryAddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(183, 183, 183))
        );

        NewFrame2.add(AddSubCategory, "cardNewSubCategory");

        NewCategoryProdactLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        NewCategoryProdactLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NewCategoryProdactLabel.setText("Επιλογή Κατηγορίας:");

        AddNewProdactButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        AddNewProdactButton.setText("Submit");
        AddNewProdactButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddNewProdactButtonActionPerformed(evt);
            }
        });

        NewProdactNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        NewProdactNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NewProdactNameLabel.setText("Εισάγετε το όνομα του προϊόντος:");

        PanelProdactCategorySelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PanelProdactCategorySelectActionPerformed(evt);
            }
        });

        PanelProdactSubCategorySelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PanelProdactSubCategorySelectActionPerformed(evt);
            }
        });

        NewSubCategoryProdactLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        NewSubCategoryProdactLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NewSubCategoryProdactLabel.setText("Επιλογή Υποκατηγορίας:");

        NewProdactStockField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        NewProdactStockField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewProdactStockFieldActionPerformed(evt);
            }
        });

        NewProdactPriceField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        NewProdactPriceField.setToolTipText("");
        NewProdactPriceField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewProdactPriceFieldActionPerformed(evt);
            }
        });

        NewProdactStockLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        NewProdactStockLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NewProdactStockLabel.setText("Aπόθεμα:");

        NewProdactPriceLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        NewProdactPriceLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NewProdactPriceLabel.setText("Κόστος:");

        NewProdactDescriptionField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        NewProdactDescriptionField.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NewProdactDescriptionField.setText(" Εισάγετε την περιγραφή του προίοντος:");

        NewProdactNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewProdactNameFieldActionPerformed(evt);
            }
        });

        NewProdactDescription.setColumns(20);
        NewProdactDescription.setLineWrap(true);
        NewProdactDescription.setRows(5);
        jScrollPane2.setViewportView(NewProdactDescription);

        javax.swing.GroupLayout AddProductsLayout = new javax.swing.GroupLayout(AddProducts);
        AddProducts.setLayout(AddProductsLayout);
        AddProductsLayout.setHorizontalGroup(
            AddProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddProductsLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(AddProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddProductsLayout.createSequentialGroup()
                        .addGroup(AddProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(PanelProdactCategorySelect, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(NewCategoryProdactLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))
                        .addGap(38, 38, 38)
                        .addGroup(AddProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(NewSubCategoryProdactLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(PanelProdactSubCategorySelect, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(34, 34, 34)
                        .addGroup(AddProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NewProdactNameLabel)
                            .addComponent(NewProdactNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 35, Short.MAX_VALUE))
                    .addGroup(AddProductsLayout.createSequentialGroup()
                        .addGroup(AddProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(NewProdactDescriptionField, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE)
                            .addComponent(jScrollPane2))
                        .addGap(87, 87, 87)
                        .addGroup(AddProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AddProductsLayout.createSequentialGroup()
                                .addGroup(AddProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(NewProdactPriceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(NewProdactPriceField, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(AddProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(NewProdactStockLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                    .addComponent(NewProdactStockField)))
                            .addComponent(AddNewProdactButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(46, 46, 46))))
        );
        AddProductsLayout.setVerticalGroup(
            AddProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddProductsLayout.createSequentialGroup()
                .addContainerGap(166, Short.MAX_VALUE)
                .addGroup(AddProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NewProdactNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NewSubCategoryProdactLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NewCategoryProdactLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AddProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PanelProdactCategorySelect, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NewProdactNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PanelProdactSubCategorySelect, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(AddProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NewProdactDescriptionField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NewProdactStockLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NewProdactPriceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AddProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(AddProductsLayout.createSequentialGroup()
                        .addGroup(AddProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NewProdactPriceField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NewProdactStockField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(AddNewProdactButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(180, 180, 180))
        );

        NewProdactPriceField.getAccessibleContext().setAccessibleName("");

        NewFrame2.add(AddProducts, "cardNewProducts");

        javax.swing.GroupLayout AddNewNamesLayout = new javax.swing.GroupLayout(AddNewNames);
        AddNewNames.setLayout(AddNewNamesLayout);
        AddNewNamesLayout.setHorizontalGroup(
            AddNewNamesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddNewNamesLayout.createSequentialGroup()
                .addComponent(SubNavigationBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(NewFrame2, javax.swing.GroupLayout.PREFERRED_SIZE, 926, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        AddNewNamesLayout.setVerticalGroup(
            AddNewNamesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SubNavigationBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(AddNewNamesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NewFrame2, javax.swing.GroupLayout.PREFERRED_SIZE, 701, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        SubNavigationBar.getAccessibleContext().setAccessibleDescription("");

        NewFrame.add(AddNewNames, "cardAddNewNames");

        SubNavigationBar1.setBackground(new java.awt.Color(0, 102, 102));

        EditCategoryButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        EditCategoryButton.setText("Κατηγοριές");
        EditCategoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditCategoryButtonActionPerformed(evt);
            }
        });

        EditSubCategoryButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        EditSubCategoryButton.setText("Υποκατηγορίες");
        EditSubCategoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditSubCategoryButtonActionPerformed(evt);
            }
        });

        EditProductButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        EditProductButton.setText("Προϊοντα");
        EditProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditProductButtonActionPerformed(evt);
            }
        });

        SubNavigationLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        SubNavigationLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SubNavigationLabel1.setText("Επεξεργασία");

        javax.swing.GroupLayout SubNavigationBar1Layout = new javax.swing.GroupLayout(SubNavigationBar1);
        SubNavigationBar1.setLayout(SubNavigationBar1Layout);
        SubNavigationBar1Layout.setHorizontalGroup(
            SubNavigationBar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SubNavigationBar1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SubNavigationBar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SubNavigationBar1Layout.createSequentialGroup()
                        .addGroup(SubNavigationBar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EditProductButton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EditCategoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EditSubCategoryButton))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(SubNavigationLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        SubNavigationBar1Layout.setVerticalGroup(
            SubNavigationBar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SubNavigationBar1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SubNavigationLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(EditCategoryButton)
                .addGap(18, 18, 18)
                .addComponent(EditSubCategoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(EditProductButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        NewFrame3.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout empty1Layout = new javax.swing.GroupLayout(empty1);
        empty1.setLayout(empty1Layout);
        empty1Layout.setHorizontalGroup(
            empty1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 926, Short.MAX_VALUE)
        );
        empty1Layout.setVerticalGroup(
            empty1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 701, Short.MAX_VALUE)
        );

        NewFrame3.add(empty1, "cardEditEmpty");

        EditCategoryName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        EditCategoryName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EditCategoryName.setText("Νέο Όνομα Κατηγορίας");

        EditCategoryField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditCategoryFieldActionPerformed(evt);
            }
        });

        AddEditCategoryButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        AddEditCategoryButton.setText("Submit");
        AddEditCategoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddEditCategoryButtonActionPerformed(evt);
            }
        });

        SelectCategoryComboBox1.setName(""); // NOI18N
        SelectCategoryComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectCategoryComboBox1ActionPerformed(evt);
            }
        });

        EditCategoryName1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        EditCategoryName1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EditCategoryName1.setText("Επιλογή Κατηγορίας");

        javax.swing.GroupLayout EditCategoryLayout = new javax.swing.GroupLayout(EditCategory);
        EditCategory.setLayout(EditCategoryLayout);
        EditCategoryLayout.setHorizontalGroup(
            EditCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EditCategoryLayout.createSequentialGroup()
                .addGap(313, 313, 313)
                .addGroup(EditCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(EditCategoryName1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SelectCategoryComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddEditCategoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EditCategoryField, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EditCategoryName, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(313, Short.MAX_VALUE))
        );
        EditCategoryLayout.setVerticalGroup(
            EditCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EditCategoryLayout.createSequentialGroup()
                .addGap(201, 201, 201)
                .addComponent(EditCategoryName1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SelectCategoryComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(EditCategoryName, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(EditCategoryField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(AddEditCategoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(178, Short.MAX_VALUE))
        );

        NewFrame3.add(EditCategory, "cardEditCategory");

        EditSubCategoryField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditSubCategoryFieldActionPerformed(evt);
            }
        });

        AddNewSubCategoryButton1.setText("Submit");
        AddNewSubCategoryButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddNewSubCategoryButton1ActionPerformed(evt);
            }
        });

        EditSubCategoryName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        EditSubCategoryName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EditSubCategoryName.setText("Νεό Όνομα Υποκατηγορίας");

        SelectCategoryComboBox2.setName(""); // NOI18N
        SelectCategoryComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectCategoryComboBox2ActionPerformed(evt);
            }
        });

        NewCategoryProdactLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        NewCategoryProdactLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NewCategoryProdactLabel3.setText("Επιλογή Κατηγορίας:");

        NewCategoryProdactLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        NewCategoryProdactLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NewCategoryProdactLabel4.setText("Επιλογή Υποκατηγορίας:");

        EditSubCategoryComboBox.setName(""); // NOI18N
        EditSubCategoryComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditSubCategoryComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout EditSubCategoryLayout = new javax.swing.GroupLayout(EditSubCategory);
        EditSubCategory.setLayout(EditSubCategoryLayout);
        EditSubCategoryLayout.setHorizontalGroup(
            EditSubCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EditSubCategoryLayout.createSequentialGroup()
                .addGap(313, 313, 313)
                .addGroup(EditSubCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(EditSubCategoryName, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(EditSubCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(EditSubCategoryField, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(EditSubCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(NewCategoryProdactLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EditSubCategoryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AddNewSubCategoryButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NewCategoryProdactLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SelectCategoryComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(313, Short.MAX_VALUE))
        );
        EditSubCategoryLayout.setVerticalGroup(
            EditSubCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EditSubCategoryLayout.createSequentialGroup()
                .addContainerGap(196, Short.MAX_VALUE)
                .addComponent(NewCategoryProdactLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SelectCategoryComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(NewCategoryProdactLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(EditSubCategoryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(EditSubCategoryName, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(EditSubCategoryField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(AddNewSubCategoryButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );

        NewFrame3.add(EditSubCategory, "cardEditSubCategory");

        EditCategoryProdactLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        EditCategoryProdactLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EditCategoryProdactLabel.setText("Επιλογή Κατηγορίας:");

        EditProdactNameButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        EditProdactNameButton.setText("Submit");
        EditProdactNameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditProdactNameButtonActionPerformed(evt);
            }
        });

        EditProdactNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        EditProdactNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EditProdactNameLabel.setText("Εισάγετε το νέο όνομα του προϊόντος:");

        EditProdactCategorySelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditProdactCategorySelectActionPerformed(evt);
            }
        });

        EditProdactSubCategorySelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditProdactSubCategorySelectActionPerformed(evt);
            }
        });

        EditSubCategoryProdactLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        EditSubCategoryProdactLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EditSubCategoryProdactLabel.setText("Επιλογή Υποκατηγορίας:");

        EditProdactDescriptionField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        EditProdactDescriptionField.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EditProdactDescriptionField.setText(" Εισάγετε την νέα περιγραφή του προίοντος:");

        EditProdactNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditProdactNameFieldActionPerformed(evt);
            }
        });

        EditProdactDescription.setColumns(20);
        EditProdactDescription.setLineWrap(true);
        EditProdactDescription.setRows(5);
        jScrollPane3.setViewportView(EditProdactDescription);

        EditProdactLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        EditProdactLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EditProdactLabel.setText("Επιλογή Προϊόντος:");

        EditProdactSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditProdactSelectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout EditProductsLayout = new javax.swing.GroupLayout(EditProducts);
        EditProducts.setLayout(EditProductsLayout);
        EditProductsLayout.setHorizontalGroup(
            EditProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EditProductsLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(EditProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EditProductsLayout.createSequentialGroup()
                        .addGroup(EditProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(EditCategoryProdactLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                            .addComponent(EditProdactCategorySelect, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(68, 68, 68)
                        .addGroup(EditProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(EditProdactSubCategorySelect, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EditSubCategoryProdactLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(EditProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EditProdactLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EditProdactSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52))
                    .addGroup(EditProductsLayout.createSequentialGroup()
                        .addGroup(EditProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(EditProdactDescriptionField, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE)
                            .addComponent(jScrollPane3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                        .addGroup(EditProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EditProdactNameField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EditProdactNameButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EditProdactNameLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(56, 56, 56))))
        );
        EditProductsLayout.setVerticalGroup(
            EditProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EditProductsLayout.createSequentialGroup()
                .addContainerGap(166, Short.MAX_VALUE)
                .addGroup(EditProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EditProductsLayout.createSequentialGroup()
                        .addGroup(EditProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EditCategoryProdactLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EditSubCategoryProdactLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(EditProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EditProdactCategorySelect, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EditProdactSubCategorySelect, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(EditProductsLayout.createSequentialGroup()
                        .addComponent(EditProdactLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(EditProdactSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34)
                .addGroup(EditProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EditProdactDescriptionField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EditProdactNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(EditProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(EditProductsLayout.createSequentialGroup()
                        .addComponent(EditProdactNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(EditProdactNameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(180, 180, 180))
        );

        NewFrame3.add(EditProducts, "cardEditProducts");

        javax.swing.GroupLayout EditNamesLayout = new javax.swing.GroupLayout(EditNames);
        EditNames.setLayout(EditNamesLayout);
        EditNamesLayout.setHorizontalGroup(
            EditNamesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EditNamesLayout.createSequentialGroup()
                .addComponent(SubNavigationBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(NewFrame3, javax.swing.GroupLayout.PREFERRED_SIZE, 926, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        EditNamesLayout.setVerticalGroup(
            EditNamesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SubNavigationBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(EditNamesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NewFrame3, javax.swing.GroupLayout.PREFERRED_SIZE, 701, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        NewFrame.add(EditNames, "cardEditNames");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainNavegationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(NewFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 1076, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MainNavegationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(NewFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 708, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SettingsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SettingsButtonActionPerformed
        cardLayout.show(NewFrame,"cardEditNames");
    }//GEN-LAST:event_SettingsButtonActionPerformed

    private void ManagerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManagerButtonActionPerformed
        cardLayout.show(NewFrame,"cardAddNewNames");
    }//GEN-LAST:event_ManagerButtonActionPerformed

    private void NewProductButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewProductButtonActionPerformed
        populateCategory(PanelProdactCategorySelect);
        cardAdd.show(NewFrame2,"cardNewProducts");
    }//GEN-LAST:event_NewProductButtonActionPerformed

    private void NewCategoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewCategoryButtonActionPerformed
        cardAdd.show(NewFrame2,"cardNewCategory");
    }//GEN-LAST:event_NewCategoryButtonActionPerformed

    private void NewPanelCategoryNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewPanelCategoryNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NewPanelCategoryNameFieldActionPerformed

    private void NewPannelAddCategoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewPannelAddCategoryButtonActionPerformed
        String addNewCategory = (String) NewPanelCategoryNameField.getText();
        if(addNewCategory == null || addNewCategory.isEmpty()){
            JOptionPane.showMessageDialog(null, "Παρακαλώ συμπληρώστε το όνομα");
            return;
        }
        
        String name = NewPanelCategoryNameField.getText();
        
        try {
            // Create DAO and insert product
            DatabaseConnection dbConnection = new DatabaseConnection();
            DataAccessObject dao = new DataAccessObject(dbConnection);
            dao.insertCategory(name);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Σφάλμα κατά την προσθήκη του προϊόντος: " + e.getMessage());
        }
        NewPanelCategoryNameField.setText("");
    }//GEN-LAST:event_NewPannelAddCategoryButtonActionPerformed

    private void NewSubCategorySubNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewSubCategorySubNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NewSubCategorySubNameActionPerformed

    private void NewSubCategoryAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewSubCategoryAddButtonActionPerformed
        String selectedCategory = (String) NewSubCategoryCategoryComboBox.getSelectedItem();
        if(selectedCategory ==null || selectedCategory.isEmpty()){
            JOptionPane.showMessageDialog(null, "Παρακαλώ επιλέξτε κατηγορία.");
            return;
        }
       
        Integer categoryId = (Integer) NewSubCategoryCategoryComboBox.getClientProperty(selectedCategory);
        String name = NewSubCategorySubName.getText();

        if(name.isEmpty()){
           JOptionPane.showMessageDialog(null, "Παρακαλώ συμπληρώστε όλα τα πεδία.");
           return;
        }
       
        try {
            // Create DAO and insert product
            DatabaseConnection dbConnection = new DatabaseConnection();
            DataAccessObject dao = new DataAccessObject(dbConnection);
            dao.insertSubCategory(categoryId, name);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Σφάλμα κατά την προσθήκη του προϊόντος: " + e.getMessage());
        }
        NewSubCategorySubName.setText("");
    }//GEN-LAST:event_NewSubCategoryAddButtonActionPerformed

    private void NewSubCategoryCategoryComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewSubCategoryCategoryComboBoxActionPerformed
         
    }//GEN-LAST:event_NewSubCategoryCategoryComboBoxActionPerformed

    private void NewSubCategoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewSubCategoryButtonActionPerformed
        populateCategory(NewSubCategoryCategoryComboBox);
        cardAdd.show(NewFrame2,"cardNewSubCategory");
    }//GEN-LAST:event_NewSubCategoryButtonActionPerformed

    private void AddNewProdactButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddNewProdactButtonActionPerformed
        String selectedSubCategory = (String) PanelProdactSubCategorySelect.getSelectedItem();
        String selectedCategory = (String) PanelProdactCategorySelect.getSelectedItem();
        if (selectedCategory == null || selectedCategory.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Παρακαλώ επιλέξτε κατηγορία.");
            return;
        }
            else if(selectedSubCategory == null || selectedSubCategory.isEmpty()){
                JOptionPane.showMessageDialog(null, "Παρακαλώ επιλέξτε υποκατηγορία.");                
            return;
            }
        Integer subCategoryId = (Integer) PanelProdactSubCategorySelect.getClientProperty(selectedSubCategory);
        String name = NewProdactNameField.getText();
        String description = NewProdactDescription.getText();
        String price = NewProdactPriceField.getText();
        String stock = NewProdactStockField.getText();
          if (name.isEmpty() || description.isEmpty() || price.isEmpty() || stock.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Παρακαλώ συμπληρώστε όλα τα πεδία.");
            return;
        }

        try {
            // Create DAO and insert product
            DatabaseConnection dbConnection = new DatabaseConnection();
            DataAccessObject dao = new DataAccessObject(dbConnection);
            dao.insertProduct(subCategoryId, name, description, price, stock);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Σφάλμα κατά την προσθήκη του προϊόντος: " + e.getMessage());
        }
        
        PanelProdactSubCategorySelect.removeAllItems();
        PanelProdactCategorySelect.removeAllItems();
        NewProdactNameField.setText("");
        NewProdactDescription.setText("");
        NewProdactPriceField.setText("");
        NewProdactStockField.setText("");
    }//GEN-LAST:event_AddNewProdactButtonActionPerformed

    private void PanelProdactSubCategorySelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PanelProdactSubCategorySelectActionPerformed
         
    }//GEN-LAST:event_PanelProdactSubCategorySelectActionPerformed

    private void NewProdactStockFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewProdactStockFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NewProdactStockFieldActionPerformed

    private void NewProdactPriceFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewProdactPriceFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NewProdactPriceFieldActionPerformed

    private void NewProdactNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewProdactNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NewProdactNameFieldActionPerformed

    private void EditCategoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditCategoryButtonActionPerformed
        cardEdit.show(NewFrame3,"cardEditCategory");
    }//GEN-LAST:event_EditCategoryButtonActionPerformed

    private void EditSubCategoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditSubCategoryButtonActionPerformed
        cardEdit.show(NewFrame3,"cardEditSubCategory");
    }//GEN-LAST:event_EditSubCategoryButtonActionPerformed

    private void EditProductButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditProductButtonActionPerformed
        cardEdit.show(NewFrame3,"cardEditProducts");
    }//GEN-LAST:event_EditProductButtonActionPerformed

    private void EditCategoryFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditCategoryFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EditCategoryFieldActionPerformed

    private void AddEditCategoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddEditCategoryButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddEditCategoryButtonActionPerformed

    private void EditSubCategoryFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditSubCategoryFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EditSubCategoryFieldActionPerformed

    private void AddNewSubCategoryButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddNewSubCategoryButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddNewSubCategoryButton1ActionPerformed

    private void SelectCategoryComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectCategoryComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SelectCategoryComboBox2ActionPerformed

    private void EditSubCategoryComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditSubCategoryComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EditSubCategoryComboBoxActionPerformed

    private void SelectCategoryComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectCategoryComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SelectCategoryComboBox1ActionPerformed

    private void PanelProdactCategorySelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PanelProdactCategorySelectActionPerformed
        PanelProdactCategorySelect.addActionListener(e -> {
            String selectedCategory = (String) PanelProdactCategorySelect.getSelectedItem();
            if (selectedCategory == null || selectedCategory.isEmpty()) {
                System.out.println("error 1");
                return;
            }

            // Retrieve the category ID from your DAO or from the JComboBox itself
            Integer categoryId = (Integer) PanelProdactCategorySelect.getClientProperty(selectedCategory); // Use a method to get the ID
            if (categoryId == null) {
                JOptionPane.showMessageDialog(null, "Κατηγορία δεν βρέθηκε.");
                return; // Early return if categoryId is null
            }

            populateSubCategory(PanelProdactSubCategorySelect, categoryId);
        });
    }//GEN-LAST:event_PanelProdactCategorySelectActionPerformed

    private void EditProdactNameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditProdactNameButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EditProdactNameButtonActionPerformed

    private void EditProdactCategorySelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditProdactCategorySelectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EditProdactCategorySelectActionPerformed

    private void EditProdactSubCategorySelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditProdactSubCategorySelectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EditProdactSubCategorySelectActionPerformed

    private void EditProdactNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditProdactNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EditProdactNameFieldActionPerformed

    private void EditProdactSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditProdactSelectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EditProdactSelectActionPerformed
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
           Main mainApp = new Main();
            mainApp.setVisible(true);
        });
    }
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddCategory;
    private javax.swing.JButton AddEditCategoryButton;
    private javax.swing.JPanel AddNewNames;
    private javax.swing.JButton AddNewProdactButton;
    private javax.swing.JButton AddNewSubCategoryButton1;
    private javax.swing.JPanel AddProducts;
    private javax.swing.JPanel AddSubCategory;
    private javax.swing.JPanel EditCategory;
    private javax.swing.JButton EditCategoryButton;
    private javax.swing.JTextField EditCategoryField;
    private javax.swing.JLabel EditCategoryName;
    private javax.swing.JLabel EditCategoryName1;
    private javax.swing.JLabel EditCategoryProdactLabel;
    private javax.swing.JPanel EditNames;
    private javax.swing.JComboBox<String> EditProdactCategorySelect;
    private javax.swing.JTextArea EditProdactDescription;
    private javax.swing.JLabel EditProdactDescriptionField;
    private javax.swing.JLabel EditProdactLabel;
    private javax.swing.JButton EditProdactNameButton;
    private javax.swing.JTextField EditProdactNameField;
    private javax.swing.JLabel EditProdactNameLabel;
    private javax.swing.JComboBox<String> EditProdactSelect;
    private javax.swing.JComboBox<String> EditProdactSubCategorySelect;
    private javax.swing.JButton EditProductButton;
    private javax.swing.JPanel EditProducts;
    private javax.swing.JPanel EditSubCategory;
    private javax.swing.JButton EditSubCategoryButton;
    private javax.swing.JComboBox<String> EditSubCategoryComboBox;
    private javax.swing.JTextField EditSubCategoryField;
    private javax.swing.JLabel EditSubCategoryName;
    private javax.swing.JLabel EditSubCategoryProdactLabel;
    private javax.swing.JPanel MainNavegationPanel;
    private javax.swing.JButton ManagerButton;
    private javax.swing.JButton NewCategoryButton;
    private javax.swing.JLabel NewCategoryProdactLabel;
    private javax.swing.JLabel NewCategoryProdactLabel3;
    private javax.swing.JLabel NewCategoryProdactLabel4;
    private javax.swing.JPanel NewFrame;
    private javax.swing.JPanel NewFrame2;
    private javax.swing.JPanel NewFrame3;
    private javax.swing.JLabel NewPanelCategoryName;
    private javax.swing.JTextField NewPanelCategoryNameField;
    private javax.swing.JButton NewPannelAddCategoryButton;
    private javax.swing.JTextArea NewProdactDescription;
    private javax.swing.JLabel NewProdactDescriptionField;
    private javax.swing.JTextField NewProdactNameField;
    private javax.swing.JLabel NewProdactNameLabel;
    private javax.swing.JTextField NewProdactPriceField;
    private javax.swing.JLabel NewProdactPriceLabel;
    private javax.swing.JTextField NewProdactStockField;
    private javax.swing.JLabel NewProdactStockLabel;
    private javax.swing.JButton NewProductButton;
    private javax.swing.JButton NewSubCategoryAddButton;
    private javax.swing.JButton NewSubCategoryButton;
    private javax.swing.JLabel NewSubCategoryCategory;
    private javax.swing.JComboBox<String> NewSubCategoryCategoryComboBox;
    private javax.swing.JLabel NewSubCategoryProdactLabel;
    private javax.swing.JLabel NewSubCategorySub;
    private javax.swing.JTextField NewSubCategorySubName;
    private javax.swing.JComboBox<String> PanelProdactCategorySelect;
    private javax.swing.JComboBox<String> PanelProdactSubCategorySelect;
    private javax.swing.JComboBox<String> SelectCategoryComboBox1;
    private javax.swing.JComboBox<String> SelectCategoryComboBox2;
    private javax.swing.JButton SettingsButton;
    private javax.swing.JPanel SplitPanel3;
    private javax.swing.JPanel SplitPanel4;
    private javax.swing.JPanel StocksPanel;
    private javax.swing.JPanel SubNavigationBar;
    private javax.swing.JPanel SubNavigationBar1;
    private javax.swing.JLabel SubNavigationLabel;
    private javax.swing.JLabel SubNavigationLabel1;
    private javax.swing.JPanel empty;
    private javax.swing.JPanel empty1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel timeLabel;
    private javax.swing.JLabel userName;
    // End of variables declaration//GEN-END:variables
}
