/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package eShopPackage;

import java.awt.CardLayout;
import java.util.List;
import javax.swing.JComboBox;
import java.util.ArrayList;
import java.util.Map;
import javax.swing.JOptionPane;

/**
 *
 * @author dimit
 */
public class Main extends javax.swing.JFrame {

    CardLayout cardLayout,cardLayout2;
    
    
    public Main() {
        initComponents();
        
        cardLayout = (CardLayout)(NewFrame.getLayout());
        cardLayout2 = (CardLayout)(NewFrame2.getLayout());
            
    }
    
    private void populateCategory(JComboBox<String> comboBox) {      
    comboBox.removeAllItems();
    comboBox.addItem("");
    DatabaseConnection dbConnection = new DatabaseConnection();
    DataAccessObject categoryDAO = new DataAccessObject(dbConnection);
    Map<Integer, String> categories = categoryDAO.getCategoryNames();
    
    for (Map.Entry<Integer, String> entry : categories.entrySet()) {
        comboBox.addItem(entry.getValue());
        comboBox.putClientProperty(entry.getValue(), entry.getKey()); // Store the ID as a property
    }
    dbConnection.closeConnection();
    }
    
    private void populateSubCategory(JComboBox<String> comboBox, int categoryId) {
    comboBox.removeAllItems();
    comboBox.addItem("");
    DatabaseConnection dbConnection = new DatabaseConnection();
    DataAccessObject categoryDAO = new DataAccessObject(dbConnection);
    Map<Integer, String> subCategories = categoryDAO.getSubCategoryNames(categoryId);
    
    for (Map.Entry<Integer, String> entry: subCategories.entrySet()) {
        comboBox.addItem(entry.getValue());
        comboBox.putClientProperty(entry.getValue(), entry.getKey()); // Store the ID as a property
    }
    dbConnection.closeConnection();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        MainNavegationPanel = new javax.swing.JPanel();
        userName = new javax.swing.JLabel();
        timeLabel = new javax.swing.JLabel();
        SettingsButton = new javax.swing.JButton();
        ManagerButton = new javax.swing.JButton();
        NewFrame = new javax.swing.JPanel();
        StocksPanel = new javax.swing.JPanel();
        AddNewPanel = new javax.swing.JPanel();
        SubNavigationBar = new javax.swing.JPanel();
        NewCategoryButton = new javax.swing.JButton();
        NewSubCategoryButton = new javax.swing.JButton();
        NewProductButton = new javax.swing.JButton();
        NewFrame2 = new javax.swing.JPanel();
        empty = new javax.swing.JPanel();
        Category = new javax.swing.JPanel();
        NewCategoryName = new javax.swing.JLabel();
        NewCategoryField = new javax.swing.JTextField();
        AddNewCategoryButton = new javax.swing.JButton();
        SubCategory = new javax.swing.JPanel();
        NewSubCategoryName = new javax.swing.JLabel();
        NewSubCategoryField = new javax.swing.JTextField();
        AddNewSubCategoryButton = new javax.swing.JButton();
        NewSubCategoryName1 = new javax.swing.JLabel();
        CategoryComboBox1 = new javax.swing.JComboBox<>();
        Prodacts = new javax.swing.JPanel();
        NewCategoryProdactLabel = new javax.swing.JLabel();
        AddNewProdactButton = new javax.swing.JButton();
        NewProdactNameLabel = new javax.swing.JLabel();
        CategoryProdactComboBox = new javax.swing.JComboBox<>();
        SubCategoryProdactComboBox = new javax.swing.JComboBox<>();
        NewSubCategoryProdactLabel = new javax.swing.JLabel();
        NewProdactStockField = new javax.swing.JTextField();
        NewProdactPriceField = new javax.swing.JTextField();
        NewProdactStockLabel = new javax.swing.JLabel();
        NewProdactPriceLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        SubCategoryList = new javax.swing.JList<>();
        NewProdactDescriptionField = new javax.swing.JLabel();
        NewProdactNameField = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        NewProdactDescription = new javax.swing.JTextArea();

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        MainNavegationPanel.setBackground(new java.awt.Color(0, 153, 153));

        userName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        userName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userName.setText("Dimitris");

        timeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        timeLabel.setText("2024-2025");

        SettingsButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        SettingsButton.setText("Απόθεμα");
        SettingsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SettingsButtonActionPerformed(evt);
            }
        });

        ManagerButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ManagerButton.setText("Προσθήκη Νέων");
        ManagerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManagerButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MainNavegationPanelLayout = new javax.swing.GroupLayout(MainNavegationPanel);
        MainNavegationPanel.setLayout(MainNavegationPanelLayout);
        MainNavegationPanelLayout.setHorizontalGroup(
            MainNavegationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainNavegationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MainNavegationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainNavegationPanelLayout.createSequentialGroup()
                        .addComponent(userName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainNavegationPanelLayout.createSequentialGroup()
                        .addComponent(timeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainNavegationPanelLayout.createSequentialGroup()
                        .addComponent(SettingsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainNavegationPanelLayout.createSequentialGroup()
                        .addComponent(ManagerButton, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        MainNavegationPanelLayout.setVerticalGroup(
            MainNavegationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainNavegationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(userName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(ManagerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SettingsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(timeLabel)
                .addContainerGap())
        );

        NewFrame.setBackground(new java.awt.Color(255, 255, 255));
        NewFrame.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout StocksPanelLayout = new javax.swing.GroupLayout(StocksPanel);
        StocksPanel.setLayout(StocksPanelLayout);
        StocksPanelLayout.setHorizontalGroup(
            StocksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1076, Short.MAX_VALUE)
        );
        StocksPanelLayout.setVerticalGroup(
            StocksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 708, Short.MAX_VALUE)
        );

        NewFrame.add(StocksPanel, "card2");

        SubNavigationBar.setBackground(new java.awt.Color(0, 102, 102));

        NewCategoryButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        NewCategoryButton.setText("Κατηγοριές");
        NewCategoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewCategoryButtonActionPerformed(evt);
            }
        });

        NewSubCategoryButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        NewSubCategoryButton.setText("Υποκατηγορίες");
        NewSubCategoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewSubCategoryButtonActionPerformed(evt);
            }
        });

        NewProductButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        NewProductButton.setText("Προϊοντα");
        NewProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewProductButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SubNavigationBarLayout = new javax.swing.GroupLayout(SubNavigationBar);
        SubNavigationBar.setLayout(SubNavigationBarLayout);
        SubNavigationBarLayout.setHorizontalGroup(
            SubNavigationBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SubNavigationBarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SubNavigationBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NewProductButton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NewCategoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NewSubCategoryButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        SubNavigationBarLayout.setVerticalGroup(
            SubNavigationBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SubNavigationBarLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(NewCategoryButton)
                .addGap(18, 18, 18)
                .addComponent(NewSubCategoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(NewProductButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        NewFrame2.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout emptyLayout = new javax.swing.GroupLayout(empty);
        empty.setLayout(emptyLayout);
        emptyLayout.setHorizontalGroup(
            emptyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 926, Short.MAX_VALUE)
        );
        emptyLayout.setVerticalGroup(
            emptyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 701, Short.MAX_VALUE)
        );

        NewFrame2.add(empty, "card5");

        NewCategoryName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        NewCategoryName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NewCategoryName.setText("New Category Name:");

        NewCategoryField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewCategoryFieldActionPerformed(evt);
            }
        });

        AddNewCategoryButton.setText("Add Category");
        AddNewCategoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddNewCategoryButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CategoryLayout = new javax.swing.GroupLayout(Category);
        Category.setLayout(CategoryLayout);
        CategoryLayout.setHorizontalGroup(
            CategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CategoryLayout.createSequentialGroup()
                .addContainerGap(183, Short.MAX_VALUE)
                .addComponent(NewCategoryName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(CategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NewCategoryField, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddNewCategoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(225, 225, 225))
        );
        CategoryLayout.setVerticalGroup(
            CategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CategoryLayout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addGroup(CategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(NewCategoryField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NewCategoryName, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(AddNewCategoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(385, Short.MAX_VALUE))
        );

        NewFrame2.add(Category, "card6");

        NewSubCategoryName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        NewSubCategoryName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        NewSubCategoryName.setText("Select Category:");

        NewSubCategoryField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewSubCategoryFieldActionPerformed(evt);
            }
        });

        AddNewSubCategoryButton.setText("Add SubCategory");
        AddNewSubCategoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddNewSubCategoryButtonActionPerformed(evt);
            }
        });

        NewSubCategoryName1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        NewSubCategoryName1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        NewSubCategoryName1.setText("New SubCategory Name:");

        CategoryComboBox1.setName(""); // NOI18N
        CategoryComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CategoryComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SubCategoryLayout = new javax.swing.GroupLayout(SubCategory);
        SubCategory.setLayout(SubCategoryLayout);
        SubCategoryLayout.setHorizontalGroup(
            SubCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SubCategoryLayout.createSequentialGroup()
                .addContainerGap(182, Short.MAX_VALUE)
                .addGroup(SubCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AddNewSubCategoryButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SubCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(SubCategoryLayout.createSequentialGroup()
                            .addComponent(NewSubCategoryName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(CategoryComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(SubCategoryLayout.createSequentialGroup()
                            .addComponent(NewSubCategoryName1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(NewSubCategoryField, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(226, 226, 226))
        );
        SubCategoryLayout.setVerticalGroup(
            SubCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SubCategoryLayout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addGroup(SubCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(CategoryComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NewSubCategoryName, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(SubCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NewSubCategoryField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NewSubCategoryName1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addComponent(AddNewSubCategoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(307, Short.MAX_VALUE))
        );

        NewFrame2.add(SubCategory, "card7");

        NewCategoryProdactLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        NewCategoryProdactLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        NewCategoryProdactLabel.setText("Επιλογή Κατηγορίας:");

        AddNewProdactButton.setText("Προσθήκη προϊόντος");
        AddNewProdactButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddNewProdactButtonActionPerformed(evt);
            }
        });

        NewProdactNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        NewProdactNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        NewProdactNameLabel.setText("Εισάγετε το όνομα του προϊόντος:");

        CategoryProdactComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CategoryProdactComboBoxActionPerformed(evt);
            }
        });

        SubCategoryProdactComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubCategoryProdactComboBoxActionPerformed(evt);
            }
        });

        NewSubCategoryProdactLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        NewSubCategoryProdactLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        NewSubCategoryProdactLabel.setText("Επιλογή Υποκατηγορίας:");

        NewProdactStockField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        NewProdactStockField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewProdactStockFieldActionPerformed(evt);
            }
        });

        NewProdactPriceField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        NewProdactPriceField.setToolTipText("");
        NewProdactPriceField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewProdactPriceFieldActionPerformed(evt);
            }
        });

        NewProdactStockLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        NewProdactStockLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        NewProdactStockLabel.setText("Aπόθεμα:");

        NewProdactPriceLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        NewProdactPriceLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        NewProdactPriceLabel.setText("Κόστος:");

        SubCategoryList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        SubCategoryList.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                SubCategoryListAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(SubCategoryList);

        NewProdactDescriptionField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        NewProdactDescriptionField.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        NewProdactDescriptionField.setText(" Εισάγετε την περιγραφή του προίοντος:");

        NewProdactNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewProdactNameFieldActionPerformed(evt);
            }
        });

        NewProdactDescription.setColumns(20);
        NewProdactDescription.setLineWrap(true);
        NewProdactDescription.setRows(5);
        jScrollPane2.setViewportView(NewProdactDescription);

        javax.swing.GroupLayout ProdactsLayout = new javax.swing.GroupLayout(Prodacts);
        Prodacts.setLayout(ProdactsLayout);
        ProdactsLayout.setHorizontalGroup(
            ProdactsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProdactsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(ProdactsLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(ProdactsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProdactsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(NewProdactDescriptionField, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(ProdactsLayout.createSequentialGroup()
                            .addGroup(ProdactsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(NewCategoryProdactLabel)
                                .addComponent(CategoryProdactComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(ProdactsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(SubCategoryProdactComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(NewSubCategoryProdactLabel))))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(ProdactsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(ProdactsLayout.createSequentialGroup()
                        .addGroup(ProdactsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(NewProdactPriceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NewProdactPriceField, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(ProdactsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(ProdactsLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(NewProdactStockLabel))
                            .addComponent(NewProdactStockField))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(AddNewProdactButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(NewProdactNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NewProdactNameLabel))
                .addGap(32, 32, 32))
        );
        ProdactsLayout.setVerticalGroup(
            ProdactsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProdactsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ProdactsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NewCategoryProdactLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NewSubCategoryProdactLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NewProdactNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ProdactsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CategoryProdactComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SubCategoryProdactComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NewProdactNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ProdactsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProdactsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(NewProdactPriceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(NewProdactStockLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(NewProdactDescriptionField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ProdactsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProdactsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(NewProdactPriceField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(NewProdactStockField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(AddNewProdactButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
                .addGap(26, 26, 26))
        );

        NewProdactPriceField.getAccessibleContext().setAccessibleName("");

        NewFrame2.add(Prodacts, "card8");

        javax.swing.GroupLayout AddNewPanelLayout = new javax.swing.GroupLayout(AddNewPanel);
        AddNewPanel.setLayout(AddNewPanelLayout);
        AddNewPanelLayout.setHorizontalGroup(
            AddNewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddNewPanelLayout.createSequentialGroup()
                .addComponent(SubNavigationBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(NewFrame2, javax.swing.GroupLayout.PREFERRED_SIZE, 926, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        AddNewPanelLayout.setVerticalGroup(
            AddNewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SubNavigationBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(AddNewPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NewFrame2, javax.swing.GroupLayout.PREFERRED_SIZE, 701, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        SubNavigationBar.getAccessibleContext().setAccessibleDescription("");

        NewFrame.add(AddNewPanel, "card1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(MainNavegationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NewFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 1076, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MainNavegationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(NewFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 708, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SettingsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SettingsButtonActionPerformed
        cardLayout.show(NewFrame,"card2");
    }//GEN-LAST:event_SettingsButtonActionPerformed

    private void ManagerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManagerButtonActionPerformed
        cardLayout.show(NewFrame,"card1");
    }//GEN-LAST:event_ManagerButtonActionPerformed

    private void NewProductButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewProductButtonActionPerformed
       populateCategory(CategoryProdactComboBox);
        cardLayout2.show(NewFrame2,"card8");
    }//GEN-LAST:event_NewProductButtonActionPerformed

    private void NewCategoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewCategoryButtonActionPerformed
        cardLayout2.show(NewFrame2,"card6");
    }//GEN-LAST:event_NewCategoryButtonActionPerformed

    private void NewCategoryFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewCategoryFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NewCategoryFieldActionPerformed

    private void AddNewCategoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddNewCategoryButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddNewCategoryButtonActionPerformed

    private void NewSubCategoryFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewSubCategoryFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NewSubCategoryFieldActionPerformed

    private void AddNewSubCategoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddNewSubCategoryButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddNewSubCategoryButtonActionPerformed

    private void CategoryComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CategoryComboBox1ActionPerformed
             
    }//GEN-LAST:event_CategoryComboBox1ActionPerformed

    private void NewSubCategoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewSubCategoryButtonActionPerformed
        populateCategory(CategoryComboBox1);
        cardLayout2.show(NewFrame2,"card7");
    }//GEN-LAST:event_NewSubCategoryButtonActionPerformed

    private void AddNewProdactButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddNewProdactButtonActionPerformed
        String selectedSubCategory = (String) SubCategoryProdactComboBox.getSelectedItem();
        if (selectedSubCategory == null || selectedSubCategory.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Παρακαλώ επιλέξτε υποκατηγορία.");
            return;
        }
        Integer subCategoryId = (Integer) SubCategoryProdactComboBox.getClientProperty(selectedSubCategory);
        String name = NewProdactNameField.getText();
        String description = NewProdactDescription.getText();
        String price = NewProdactPriceField.getText();
        String stock = NewProdactStockField.getText();
          if (name.isEmpty() || description.isEmpty() || price.isEmpty() || stock.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Παρακαλώ συμπληρώστε όλα τα πεδία.");
            return;
        }

        try {
            // Create DAO and insert product
            DatabaseConnection dbConnection = new DatabaseConnection();
            DataAccessObject dao = new DataAccessObject(dbConnection);
            dao.insertProduct(subCategoryId, name, description, price, stock);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Σφάλμα κατά την προσθήκη του προϊόντος: " + e.getMessage());
        }
    
    }//GEN-LAST:event_AddNewProdactButtonActionPerformed

    private void CategoryProdactComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CategoryProdactComboBoxActionPerformed
        CategoryProdactComboBox.addActionListener(e -> {
        String selectedCategory = (String) CategoryProdactComboBox.getSelectedItem();
            if (selectedCategory == null || selectedCategory.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Παρακαλώ επιλέξτε κατηγορία.");
                return;
            }
            Integer categoryId = (Integer) CategoryProdactComboBox.getClientProperty(selectedCategory);
            populateSubCategory(SubCategoryProdactComboBox, categoryId);
        });
        
    }//GEN-LAST:event_CategoryProdactComboBoxActionPerformed

    private void SubCategoryProdactComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubCategoryProdactComboBoxActionPerformed
         
    }//GEN-LAST:event_SubCategoryProdactComboBoxActionPerformed

    private void SubCategoryListAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_SubCategoryListAncestorAdded
      
    }//GEN-LAST:event_SubCategoryListAncestorAdded

    private void NewProdactStockFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewProdactStockFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NewProdactStockFieldActionPerformed

    private void NewProdactPriceFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewProdactPriceFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NewProdactPriceFieldActionPerformed

    private void NewProdactNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewProdactNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NewProdactNameFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }
    
   
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddNewCategoryButton;
    private javax.swing.JPanel AddNewPanel;
    private javax.swing.JButton AddNewProdactButton;
    private javax.swing.JButton AddNewSubCategoryButton;
    private javax.swing.JPanel Category;
    private javax.swing.JComboBox<String> CategoryComboBox1;
    private javax.swing.JComboBox<String> CategoryProdactComboBox;
    private javax.swing.JPanel MainNavegationPanel;
    private javax.swing.JButton ManagerButton;
    private javax.swing.JButton NewCategoryButton;
    private javax.swing.JTextField NewCategoryField;
    private javax.swing.JLabel NewCategoryName;
    private javax.swing.JLabel NewCategoryProdactLabel;
    private javax.swing.JPanel NewFrame;
    private javax.swing.JPanel NewFrame2;
    private javax.swing.JTextArea NewProdactDescription;
    private javax.swing.JLabel NewProdactDescriptionField;
    private javax.swing.JTextField NewProdactNameField;
    private javax.swing.JLabel NewProdactNameLabel;
    private javax.swing.JTextField NewProdactPriceField;
    private javax.swing.JLabel NewProdactPriceLabel;
    private javax.swing.JTextField NewProdactStockField;
    private javax.swing.JLabel NewProdactStockLabel;
    private javax.swing.JButton NewProductButton;
    private javax.swing.JButton NewSubCategoryButton;
    private javax.swing.JTextField NewSubCategoryField;
    private javax.swing.JLabel NewSubCategoryName;
    private javax.swing.JLabel NewSubCategoryName1;
    private javax.swing.JLabel NewSubCategoryProdactLabel;
    private javax.swing.JPanel Prodacts;
    private javax.swing.JButton SettingsButton;
    private javax.swing.JPanel StocksPanel;
    private javax.swing.JPanel SubCategory;
    private javax.swing.JList<String> SubCategoryList;
    private javax.swing.JComboBox<String> SubCategoryProdactComboBox;
    private javax.swing.JPanel SubNavigationBar;
    private javax.swing.JPanel empty;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel timeLabel;
    private javax.swing.JLabel userName;
    // End of variables declaration//GEN-END:variables
}
