/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package eShopPackage;

import java.awt.CardLayout;
import java.util.List;
import javax.swing.JComboBox;
import java.util.ArrayList;

/**
 *
 * @author dimit
 */
public class Main extends javax.swing.JFrame {

    CardLayout cardLayout,cardLayout2;
    
    public Main() {
        initComponents();
        
        cardLayout = (CardLayout)(NewFrame.getLayout());
        cardLayout2 = (CardLayout)(NewFrame2.getLayout());
            
    }
    
    private void populateCategory(JComboBox<String> comboBox) {
    comboBox.removeAllItems();
    comboBox.addItem("");
    DatabaseConnection dbConnection = new DatabaseConnection();
    DataAccessObject categoryDAO = new DataAccessObject(dbConnection);
    List<String> categories = categoryDAO.getCategoryNames();
    
    for (String category : categories) {
        comboBox.addItem(category);
    }
    dbConnection.closeConnection();
    }
    
    private void populateSubCategory(JComboBox<String> comboBox) {
    comboBox.removeAllItems();
    comboBox.addItem("");
    DatabaseConnection dbConnection = new DatabaseConnection();
    DataAccessObject categoryDAO = new DataAccessObject(dbConnection);
    List<String> categories = categoryDAO.getSubCategoryNames();
    
    for (String category : categories) {
        comboBox.addItem(category);
    }
    dbConnection.closeConnection();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainNavegationPanel = new javax.swing.JPanel();
        userName = new javax.swing.JLabel();
        timeLabel = new javax.swing.JLabel();
        SettingsButton = new javax.swing.JButton();
        ManagerButton = new javax.swing.JButton();
        NewFrame = new javax.swing.JPanel();
        StocksPanel = new javax.swing.JPanel();
        AddNewPanel = new javax.swing.JPanel();
        SubNavigationBar = new javax.swing.JPanel();
        NewCategoryButton = new javax.swing.JButton();
        NewSubCategoryButton = new javax.swing.JButton();
        NewProductButton = new javax.swing.JButton();
        NewFrame2 = new javax.swing.JPanel();
        empty = new javax.swing.JPanel();
        Category = new javax.swing.JPanel();
        NewCategoryName = new javax.swing.JLabel();
        NewCategoryField = new javax.swing.JTextField();
        AddNewCategoryButton = new javax.swing.JButton();
        SubCategory = new javax.swing.JPanel();
        NewSubCategoryName = new javax.swing.JLabel();
        NewSubCategoryField = new javax.swing.JTextField();
        AddNewSubCategoryButton = new javax.swing.JButton();
        NewSubCategoryName1 = new javax.swing.JLabel();
        CategoryComboBox1 = new javax.swing.JComboBox<>();
        Prodacts = new javax.swing.JPanel();
        NewCategoryName1 = new javax.swing.JLabel();
        NewProdactField = new javax.swing.JTextField();
        AddNewProdactButton = new javax.swing.JButton();
        NewProdactName = new javax.swing.JLabel();
        CategoryComboBox = new javax.swing.JComboBox<>();
        SubCategoryComboBox = new javax.swing.JComboBox<>();
        NewSubCategoryName4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        SubCategoryList = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        MainNavegationPanel.setBackground(new java.awt.Color(0, 153, 153));

        userName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        userName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userName.setText("Dimitris");

        timeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        timeLabel.setText("2024-2025");

        SettingsButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        SettingsButton.setText("Απόθεμα");
        SettingsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SettingsButtonActionPerformed(evt);
            }
        });

        ManagerButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ManagerButton.setText("Προσθήκη Νέων");
        ManagerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManagerButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MainNavegationPanelLayout = new javax.swing.GroupLayout(MainNavegationPanel);
        MainNavegationPanel.setLayout(MainNavegationPanelLayout);
        MainNavegationPanelLayout.setHorizontalGroup(
            MainNavegationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainNavegationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MainNavegationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainNavegationPanelLayout.createSequentialGroup()
                        .addComponent(userName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainNavegationPanelLayout.createSequentialGroup()
                        .addComponent(timeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainNavegationPanelLayout.createSequentialGroup()
                        .addComponent(SettingsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainNavegationPanelLayout.createSequentialGroup()
                        .addComponent(ManagerButton, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        MainNavegationPanelLayout.setVerticalGroup(
            MainNavegationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainNavegationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(userName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(ManagerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SettingsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(timeLabel)
                .addContainerGap())
        );

        NewFrame.setBackground(new java.awt.Color(255, 255, 255));
        NewFrame.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout StocksPanelLayout = new javax.swing.GroupLayout(StocksPanel);
        StocksPanel.setLayout(StocksPanelLayout);
        StocksPanelLayout.setHorizontalGroup(
            StocksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1076, Short.MAX_VALUE)
        );
        StocksPanelLayout.setVerticalGroup(
            StocksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 708, Short.MAX_VALUE)
        );

        NewFrame.add(StocksPanel, "card2");

        SubNavigationBar.setBackground(new java.awt.Color(0, 102, 102));

        NewCategoryButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        NewCategoryButton.setText("Κατηγοριές");
        NewCategoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewCategoryButtonActionPerformed(evt);
            }
        });

        NewSubCategoryButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        NewSubCategoryButton.setText("Υποκατηγορίες");
        NewSubCategoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewSubCategoryButtonActionPerformed(evt);
            }
        });

        NewProductButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        NewProductButton.setText("Προϊοντα");
        NewProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewProductButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SubNavigationBarLayout = new javax.swing.GroupLayout(SubNavigationBar);
        SubNavigationBar.setLayout(SubNavigationBarLayout);
        SubNavigationBarLayout.setHorizontalGroup(
            SubNavigationBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SubNavigationBarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SubNavigationBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NewProductButton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NewCategoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NewSubCategoryButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        SubNavigationBarLayout.setVerticalGroup(
            SubNavigationBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SubNavigationBarLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(NewCategoryButton)
                .addGap(18, 18, 18)
                .addComponent(NewSubCategoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(NewProductButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        NewFrame2.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout emptyLayout = new javax.swing.GroupLayout(empty);
        empty.setLayout(emptyLayout);
        emptyLayout.setHorizontalGroup(
            emptyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 926, Short.MAX_VALUE)
        );
        emptyLayout.setVerticalGroup(
            emptyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 701, Short.MAX_VALUE)
        );

        NewFrame2.add(empty, "card5");

        NewCategoryName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        NewCategoryName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NewCategoryName.setText("New Category Name:");

        NewCategoryField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewCategoryFieldActionPerformed(evt);
            }
        });

        AddNewCategoryButton.setText("Add Category");
        AddNewCategoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddNewCategoryButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CategoryLayout = new javax.swing.GroupLayout(Category);
        Category.setLayout(CategoryLayout);
        CategoryLayout.setHorizontalGroup(
            CategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CategoryLayout.createSequentialGroup()
                .addContainerGap(183, Short.MAX_VALUE)
                .addComponent(NewCategoryName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(CategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NewCategoryField, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddNewCategoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(225, 225, 225))
        );
        CategoryLayout.setVerticalGroup(
            CategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CategoryLayout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addGroup(CategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(NewCategoryField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NewCategoryName, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(AddNewCategoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(385, Short.MAX_VALUE))
        );

        NewFrame2.add(Category, "card6");

        NewSubCategoryName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        NewSubCategoryName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        NewSubCategoryName.setText("Select Category:");

        NewSubCategoryField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewSubCategoryFieldActionPerformed(evt);
            }
        });

        AddNewSubCategoryButton.setText("Add SubCategory");
        AddNewSubCategoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddNewSubCategoryButtonActionPerformed(evt);
            }
        });

        NewSubCategoryName1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        NewSubCategoryName1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        NewSubCategoryName1.setText("New SubCategory Name:");

        CategoryComboBox1.setName(""); // NOI18N
        CategoryComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CategoryComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SubCategoryLayout = new javax.swing.GroupLayout(SubCategory);
        SubCategory.setLayout(SubCategoryLayout);
        SubCategoryLayout.setHorizontalGroup(
            SubCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SubCategoryLayout.createSequentialGroup()
                .addContainerGap(182, Short.MAX_VALUE)
                .addGroup(SubCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AddNewSubCategoryButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SubCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(SubCategoryLayout.createSequentialGroup()
                            .addComponent(NewSubCategoryName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(CategoryComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(SubCategoryLayout.createSequentialGroup()
                            .addComponent(NewSubCategoryName1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(NewSubCategoryField, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(226, 226, 226))
        );
        SubCategoryLayout.setVerticalGroup(
            SubCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SubCategoryLayout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addGroup(SubCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(CategoryComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NewSubCategoryName, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(SubCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NewSubCategoryField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NewSubCategoryName1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addComponent(AddNewSubCategoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(307, Short.MAX_VALUE))
        );

        NewFrame2.add(SubCategory, "card7");

        NewCategoryName1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        NewCategoryName1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        NewCategoryName1.setText("Select Category:");

        NewProdactField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewProdactFieldActionPerformed(evt);
            }
        });

        AddNewProdactButton.setText("Add SubCategory");
        AddNewProdactButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddNewProdactButtonActionPerformed(evt);
            }
        });

        NewProdactName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        NewProdactName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        NewProdactName.setText("New Prodact Name:");

        CategoryComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CategoryComboBoxActionPerformed(evt);
            }
        });

        SubCategoryComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubCategoryComboBoxActionPerformed(evt);
            }
        });

        NewSubCategoryName4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        NewSubCategoryName4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        NewSubCategoryName4.setText("Select SubCategory:");

        SubCategoryList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(SubCategoryList);

        javax.swing.GroupLayout ProdactsLayout = new javax.swing.GroupLayout(Prodacts);
        Prodacts.setLayout(ProdactsLayout);
        ProdactsLayout.setHorizontalGroup(
            ProdactsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProdactsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ProdactsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(ProdactsLayout.createSequentialGroup()
                        .addGroup(ProdactsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ProdactsLayout.createSequentialGroup()
                                .addComponent(NewCategoryName1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(NewSubCategoryName4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(NewProdactName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ProdactsLayout.createSequentialGroup()
                                .addComponent(CategoryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(SubCategoryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(NewProdactField, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(AddNewProdactButton, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 88, Short.MAX_VALUE)))
                .addContainerGap())
        );
        ProdactsLayout.setVerticalGroup(
            ProdactsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProdactsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ProdactsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NewCategoryName1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NewSubCategoryName4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NewProdactName, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ProdactsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CategoryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SubCategoryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NewProdactField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddNewProdactButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 564, Short.MAX_VALUE)
                .addContainerGap())
        );

        NewFrame2.add(Prodacts, "card8");

        javax.swing.GroupLayout AddNewPanelLayout = new javax.swing.GroupLayout(AddNewPanel);
        AddNewPanel.setLayout(AddNewPanelLayout);
        AddNewPanelLayout.setHorizontalGroup(
            AddNewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddNewPanelLayout.createSequentialGroup()
                .addComponent(SubNavigationBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(NewFrame2, javax.swing.GroupLayout.PREFERRED_SIZE, 926, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        AddNewPanelLayout.setVerticalGroup(
            AddNewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SubNavigationBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(AddNewPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NewFrame2, javax.swing.GroupLayout.PREFERRED_SIZE, 701, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        SubNavigationBar.getAccessibleContext().setAccessibleDescription("");

        NewFrame.add(AddNewPanel, "card1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainNavegationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NewFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 1076, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MainNavegationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(NewFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 708, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SettingsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SettingsButtonActionPerformed
        cardLayout.show(NewFrame,"card2");
    }//GEN-LAST:event_SettingsButtonActionPerformed

    private void ManagerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManagerButtonActionPerformed
        cardLayout.show(NewFrame,"card1");
    }//GEN-LAST:event_ManagerButtonActionPerformed

    private void NewProductButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewProductButtonActionPerformed
       populateCategory(CategoryComboBox);
       populateSubCategory(SubCategoryComboBox);
        cardLayout2.show(NewFrame2,"card8");
    }//GEN-LAST:event_NewProductButtonActionPerformed

    private void NewCategoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewCategoryButtonActionPerformed
        cardLayout2.show(NewFrame2,"card6");
    }//GEN-LAST:event_NewCategoryButtonActionPerformed

    private void NewCategoryFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewCategoryFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NewCategoryFieldActionPerformed

    private void AddNewCategoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddNewCategoryButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddNewCategoryButtonActionPerformed

    private void NewSubCategoryFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewSubCategoryFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NewSubCategoryFieldActionPerformed

    private void AddNewSubCategoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddNewSubCategoryButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddNewSubCategoryButtonActionPerformed

    private void CategoryComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CategoryComboBox1ActionPerformed
             
    }//GEN-LAST:event_CategoryComboBox1ActionPerformed

    private void NewSubCategoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewSubCategoryButtonActionPerformed
        populateCategory(CategoryComboBox1);
        cardLayout2.show(NewFrame2,"card7");
    }//GEN-LAST:event_NewSubCategoryButtonActionPerformed

    private void NewProdactFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewProdactFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NewProdactFieldActionPerformed

    private void AddNewProdactButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddNewProdactButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddNewProdactButtonActionPerformed

    private void CategoryComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CategoryComboBoxActionPerformed
       
    }//GEN-LAST:event_CategoryComboBoxActionPerformed

    private void SubCategoryComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubCategoryComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SubCategoryComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }
    
   
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddNewCategoryButton;
    private javax.swing.JPanel AddNewPanel;
    private javax.swing.JButton AddNewProdactButton;
    private javax.swing.JButton AddNewSubCategoryButton;
    private javax.swing.JPanel Category;
    private javax.swing.JComboBox<String> CategoryComboBox;
    private javax.swing.JComboBox<String> CategoryComboBox1;
    private javax.swing.JPanel MainNavegationPanel;
    private javax.swing.JButton ManagerButton;
    private javax.swing.JButton NewCategoryButton;
    private javax.swing.JTextField NewCategoryField;
    private javax.swing.JLabel NewCategoryName;
    private javax.swing.JLabel NewCategoryName1;
    private javax.swing.JPanel NewFrame;
    private javax.swing.JPanel NewFrame2;
    private javax.swing.JTextField NewProdactField;
    private javax.swing.JLabel NewProdactName;
    private javax.swing.JButton NewProductButton;
    private javax.swing.JButton NewSubCategoryButton;
    private javax.swing.JTextField NewSubCategoryField;
    private javax.swing.JLabel NewSubCategoryName;
    private javax.swing.JLabel NewSubCategoryName1;
    private javax.swing.JLabel NewSubCategoryName4;
    private javax.swing.JPanel Prodacts;
    private javax.swing.JButton SettingsButton;
    private javax.swing.JPanel StocksPanel;
    private javax.swing.JPanel SubCategory;
    private javax.swing.JComboBox<String> SubCategoryComboBox;
    private javax.swing.JList<String> SubCategoryList;
    private javax.swing.JPanel SubNavigationBar;
    private javax.swing.JPanel empty;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel timeLabel;
    private javax.swing.JLabel userName;
    // End of variables declaration//GEN-END:variables
}
